spring:
  datasource:
    url: jdbc:mysql://localhost:3306/likelion #본인 데베 주소쓰기
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: rlaxogjs5656@gmail.com #본인 지메일
    password: "${MAIL_PASSWORD}" #16자리 앱키 공백없이!
    scheduled:
      target-email: rlaxogjs5656@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: "YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo1NDMyMTBhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5eg=="
  access-token-validity-in-milliseconds: 3600000

kakao:
  client-id: d757f67d9872d066272f59268207d238 #카카오 개발자 탬에서 본인거 복붙하기 꼭 비즈앱 전환해서 이메일 필수로 받아야함!
  client-secret: ""
  redirect-uri: http://localhost:8080/login/oauth2/code/kakao
  token-url: https://kauth.kakao.com/oauth/token
  user-info-url: https://kapi.kakao.com/v2/user/me

token:
  expire:
    time: 1800000
